version: "3.8"

services:
  postgres:
    image: postgres:13.5
    container_name: engmasterai-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: engmasterai
    volumes:
      - engmasterai_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: engmasterai-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - engmasterai_redis:/data
    command: redis-server --appendonly yes

volumes:
  engmasterai_postgres:
  engmasterai_redis:
